/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "machineinfo" CASCADE;

CREATE TABLE "machineinfo" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "client_key" TEXT NOT NULL,
  "memory_mem_total" INTEGER NOT NULL,
  "memory_mem_available" INTEGER NOT NULL,
  "memory_mem_free" INTEGER NOT NULL,
  "cpu_idle_time" REAL NOT NULL,
  "cpu_use_time" REAL NOT NULL,
  "process_total" INTEGER NOT NULL,
  "process_running" INTEGER NOT NULL,
  "process_blocked" INTEGER NOT NULL,
  "system_info_system_ip" TEXT NOT NULL,
  "system_info_system_name" TEXT NOT NULL,
  "time_stamp" BIGINT NOT NULL);

